info/__init__.py
import logging
from logging.handlers import RotatingFileHandler
from flask import Flask, config
from flask_session import Session
from flask_sqlalchemy import SQLAlchemy
from flask_wtf import CSRFProtect
from flask_wtf.csrf import generate_csrf
from redis import StrictRedis

from config import config

# 初始化数据库
# 在flask很多扩展里可以先初始化扩展的对象，再用init_app初始化


db = SQLAlchemy()
redis_store = None

def setup_log(config_name):
    """配置日志"""

    # 设置日志的记录等级
    logging.basicConfig(level=config[config_name].LOG_LEVEL)  # 调试debug级

    # 创建日志记录器，指明日志保存的路径、每个日志文件的最大大小、保存的日志文件个数上限
    file_log_handler = RotatingFileHandler("logs/log", maxBytes=1024 * 1024 * 100, backupCount=10)

    # 创建日志记录的格式 日志等级 输入日志信息的文件名 行数 日志信息
    formatter = logging.Formatter('%(levelname)s %(filename)s:%(lineno)d %(message)s')

    # 为刚创建的日志记录器设置日志记录格式
    file_log_handler.setFormatter(formatter)

    # 为全局的日志工具对象（flask app使用的）添加日志记录器
    logging.getLogger().addHandler(file_log_handler)

# create_app类似工厂方法
def create_app(config_name):
    # 配置日志并传入配置名字，以便能获取到指定配置的文件日志等级
    setup_log(config_name)
    # 创建flask对象
    app = Flask(__name__)

    # 从app加载配置
    app.config.from_object(config[config_name])

    db.init_app(app)

    # 初始化Redis对象
    global redis_store
    redis_store = StrictRedis(host=config[config_name].REDIS_HOST,port=config[config_name].REDIS_PORT,decode_responses=True)

    # 开启CSRF保护,只做服务器验证功能
    # 已经帮我们做了：从cookie中取出随机值，从表单中取出随机值，进行校验，并响应校验结果
    # 我们需要做：1.在页面加载的时候，往cookie中添加csrf_token,并且在表单中添加一个隐藏的csrf_token  2.因为没有使用表单，所以在ajax请求中带有csrf_token就行
    CSRFProtect(app)

    #设置session保存指定位置
    Session(app)

    @app.after_request
    def after_request(response):
        # 生成随机的csrf_token的值
        csrf_token = generate_csrf()
        # 设置一个cookie
        response.set_cookie("csrf_token",csrf_token)
        return response

    from flask import render_template, g
    from info.utils.set_filters import user_login_data
    @app.errorhandler(404)
    @user_login_data
    def page_not_found(_):
        user = g.user
        data = {"user_info": user.to_dict() if user else None}
        return render_template('news/404.html', data=data)
        return app



    # 注册蓝图
    from info.modules.index import index_blue
    app.register_blueprint(index_blue)

    from info.modules.passport import passport_blue
    app.register_blueprint(passport_blue)

    from info.utils.set_filters import set_filter
    app.add_template_filter(set_filter,"set_class")

    from info.modules.news import news_blue
    app.register_blueprint(news_blue)

    from info.modules.profile import profile_blue
    app.register_blueprint(profile_blue)

    from info.modules.admin import admin_blue
    app.register_blueprint(admin_blue)

    return app

info/libs/__init__.py
# 第三方提供的SDK放在该文件夹下

info/modules/__init__.py
# 用于存放所有业务逻辑的功能模块，如首页、个人中心、新闻详情页、后台管理

info/modules/admin/__init__.py
from flask import Blueprint

# 创建蓝图对象
admin_blue = Blueprint("admin",__name__,url_prefix='/admin')

from .views import *


@admin_blue.before_request
def before_request():
    # 判断如果不是登录页面的请求
    if not request.url.endswith(url_for("admin.admin_login")):
        user_id = session.get("user_id")
        is_admin = session.get("is_admin", False)

        if not user_id or not is_admin:
            # 判断当前是否有用户登录，或者是否是管理员，如果不是，直接重定向到项目主页
            return redirect('/')

info/modules/admin/views.py
import time
from datetime import datetime, timedelta
from flask import render_template, request, current_app, g, redirect, url_for, session, jsonify

from info import constants, db
from info.models import User, News, Category
from info.modules.admin import admin_blue
from info.utils.image_storage import storage
from info.utils.response_code import RET
from info.utils.set_filters import user_login_data

@admin_blue.route('/add_category', methods=["POST"])
def add_category():
    """修改或者添加分类"""

    category_id = request.json.get("id")
    category_name = request.json.get("name")
    if not category_name:
        return jsonify(errno=RET.PARAMERR, errmsg="参数错误")
    # 判断是否有分类id
    if category_id:
        try:
            category = Category.query.get(category_id)
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.DBERR, errmsg="查询数据失败")

        if not category:
            return jsonify(errno=RET.NODATA, errmsg="未查询到分类信息")

        category.name = category_name
    else:
        # 如果没有分类id，则是添加分类
        category = Category()
        category.name = category_name
        db.session.add(category)

    try:
        db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        db.session.rollback()
        return jsonify(errno=RET.DBERR, errmsg="保存数据失败")
    return jsonify(errno=RET.OK, errmsg="保存数据成功")

@admin_blue.route('/news_category')
def get_news_category():
    # 获取所有的分类数据
    categories = Category.query.all()
    # 定义列表保存分类数据
    categories_dicts = []

    for category in categories:
        # 获取字典
        cate_dict = category.to_dict()
        # 拼接内容
        categories_dicts.append(cate_dict)

    categories_dicts.pop(0)
    # 返回内容
    return render_template('admin/news_type.html', data={"categories": categories_dicts})


@admin_blue.route('/news_edit_detail', methods=["GET", "POST"])
def news_edit_detail():
    """新闻编辑详情"""
    if request.method == "GET":
        """新闻编辑详情"""

        # 获取参数
        news_id = request.args.get("news_id")

        if not news_id:
            return render_template('admin/news_edit_detail.html', data={"errmsg": "未查询到此新闻"})

        # 查询新闻
        news = None
        try:
            news = News.query.get(news_id)
        except Exception as e:
            current_app.logger.error(e)

        if not news:
            return render_template('admin/news_edit_detail.html', data={"errmsg": "未查询到此新闻"})

        # 查询分类的数据
        categories = Category.query.all()
        categories_li = []
        for category in categories:
            c_dict = category.to_dict()
            c_dict["is_selected"] = False
            if category.id == news.category_id:
                c_dict["is_selected"] = True
            categories_li.append(c_dict)
        # 移除`最新`分类
        categories_li.pop(0)

        data = {"news": news.to_dict(), "categories": categories_li}
        return render_template('admin/news_edit_detail.html', data=data)


    news_id = request.form.get("news_id")
    title = request.form.get("title")
    digest = request.form.get("digest")
    content = request.form.get("content")
    index_image = request.files.get("index_image")
    category_id = request.form.get("category_id")
    # 1.1 判断数据是否有值
    if not all([title, digest, content, category_id]):
        return jsonify(errno=RET.PARAMERR, errmsg="参数有误")

    news = None
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)
    if not news:
        return jsonify(errno=RET.NODATA, errmsg="未查询到新闻数据")

    # 1.2 尝试读取图片
    if index_image:
        try:
            index_image = index_image.read()
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.PARAMERR, errmsg="参数有误")

        # 2. 将标题图片上传到七牛
        try:
            key = storage(index_image)
        except Exception as e:
            current_app.logger.error(e)
            return jsonify(errno=RET.THIRDERR, errmsg="上传图片错误")
        news.index_image_url = constants.QINIU_DOMIN_PREFIX + key

    # 3. 设置相关数据
    news.title = title
    news.digest = digest
    news.content = content
    news.category_id = category_id

    # 4. 保存到数据库
    try:
        db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        db.session.rollback()
        return jsonify(errno=RET.DBERR, errmsg="保存数据失败")
    # 5. 返回结果
    return jsonify(errno=RET.OK, errmsg="编辑成功")

@admin_blue.route('/news_edit')
def news_edit():
    """返回新闻列表"""

    page = request.args.get("p", 1)
    keywords = request.args.get("keywords", "")
    try:
        page = int(page)
    except Exception as e:
        current_app.logger.error(e)
        page = 1

    news_list = []
    current_page = 1
    total_page = 1

    try:
        filters = []
        # 如果有关键词
        if keywords:
            # 添加关键词的检索选项
            filters.append(News.title.contains(keywords))

        # 查询
        paginate = News.query.filter(*filters).order_by(News.create_time.desc()).paginate(page, constants.ADMIN_NEWS_PAGE_MAX_COUNT, False)

        news_list = paginate.items
        current_page = paginate.page
        total_page = paginate.pages
    except Exception as e:
        current_app.logger.error(e)

    news_dict_list = []
    for news in news_list:
        news_dict_list.append(news.to_basic_dict())

    data = {
        "total_page": total_page,
        "current_page": current_page,
        "news_list": news_dict_list
    }

    return render_template('admin/news_edit.html', data=data)




@admin_blue.route('/news_review_detail', methods=["GET", "POST"])
def news_review_detail():
    """新闻审核"""
    if request.method == "GET":
        # 获取新闻id
        news_id = request.args.get("news_id")
        if not news_id:
            return render_template('admin/news_review_detail.html', data={"errmsg": "未查询到此新闻"})

        # 通过id查询新闻
        news = None
        try:
            news = News.query.get(news_id)
        except Exception as e:
            current_app.logger.error(e)

        if not news:
            return render_template('admin/news_review_detail.html', data={"errmsg": "未查询到此新闻"})

        # 返回数据
        data = {"news": news.to_dict()}
        return render_template('admin/news_review_detail.html', data=data)
    # 1.获取参数
    news_id = request.json.get("news_id")
    action = request.json.get("action")

    # 2.判断参数
    if not all([news_id, action]):
        return jsonify(errno=RET.PARAMERR, errmsg="参数错误")
    if action not in ("accept", "reject"):
        return jsonify(errno=RET.PARAMERR, errmsg="参数错误")

    news = None
    try:
        # 3.查询新闻
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)

    if not news:
        return jsonify(errno=RET.NODATA, errmsg="未查询到数据")

    # 4.根据不同的状态设置不同的值
    if action == "accept":
        news.status = 0
    else:
        # 拒绝通过，需要获取原因
        reason = request.json.get("reason")
        if not reason:
            return jsonify(errno=RET.PARAMERR, errmsg="参数错误")
        news.reason = reason
        news.status = -1

    # 保存数据库
    try:
        db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        db.session.rollback()
        return jsonify(errno=RET.DBERR, errmsg="数据保存失败")
    return jsonify(errno=RET.OK, errmsg="操作成功")





@admin_blue.route('/news_review')
def news_review():
    """返回待审核新闻列表"""

    page = request.args.get("p", 1)
    keywords = request.args.get("keywords", "")

    try:
        page = int(page)
    except Exception as e:
        current_app.logger.error(e)
        page = 1

    news_list = []
    current_page = 1
    total_page = 1



    try:
        filters = [News.status != 0]
        # 如果有关键词
        if keywords:
            # 添加关键词的检索选项
            filters.append(News.title.contains(keywords))

        paginate = News.query.filter(*filters) \
            .order_by(News.create_time.desc()) \
            .paginate(page, constants.ADMIN_NEWS_PAGE_MAX_COUNT, False)

        news_list = paginate.items
        current_page = paginate.page
        total_page = paginate.pages
    except Exception as e:
        current_app.logger.error(e)

    news_dict_list = []
    for news in news_list:
        news_dict_list.append(news.to_review_dict())

    data = {
            "total_page": total_page,
            "current_page": current_page,
            "news_list": news_dict_list
    }
    return render_template("admin/news_review.html", data=data)




@admin_blue.route('/user_list')
def user_list():
    """获取用户列表"""

    # 获取参数
    page = request.args.get("p", 1)
    try:
        page = int(page)
    except Exception as e:
        current_app.logger.error(e)
        page = 1

    # 设置变量默认值
    users = []
    current_page = 1
    total_page = 1

    # 查询数据
    try:
        paginate = User.query.filter(User.is_admin == False).order_by(User.last_login.desc()).paginate(page, constants.ADMIN_USER_PAGE_MAX_COUNT, False)
        users = paginate.items
        current_page = paginate.page
        total_page = paginate.pages
    except Exception as e:
        current_app.logger.error(e)

    # 将模型列表转成字典列表
    users_list = []
    for user in users:
        users_list.append(user.to_admin_dict())

    data = {"total_page": total_page,
            "current_page": current_page,
            "users": users_list}
    return render_template('admin/user_list.html',data=data)

@admin_blue.route('/user_count')
def user_count():
    total_count = 0
    try:
        total_count = User.query.filter(User.is_admin == False).count()
    except Exception as e:
        current_app.logger.error(e)

    # 查询月新增数
    mon_count = 0
    try:
        now = time.localtime()
        mon_begin = '%d-%02d-01' % (now.tm_year, now.tm_mon)
        mon_begin_date = datetime.strptime(mon_begin, '%Y-%m-%d')

info/modules/index/__init__.py
from flask import Blueprint

# 创建蓝图对象
index_blue = Blueprint("index",__name__)

from .views import *

info/modules/index/views.py
from flask import render_template, current_app, session, request, jsonify, g
from info import constants
from info.models import User, News, Category
from info.utils.response_code import RET
from info.utils.set_filters import user_login_data
from . import index_blue


@index_blue.route("/news_list")
def news_list():
    """
    获取首页新闻数据
    :return:
    """
    # 1.获取参数
    # 新闻分类的id
    cid = request.args.get("cid", "1")
    # 页数，不传即获取第1页
    page = request.args.get("page", "1")
    # 每页多少条数据，如果不传，默认10条
    per_page = request.args.get("per_page", 10)

    # 2.校验参数
    try:
        cid = int(cid)
        page = int(page)
        per_page = int(per_page)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR, errmsg="参数错误")

    filters = [News.status == 0]
    if cid != 1:  # 代表查询的不是最新的数据
        # 需要添加条件
        filters.append(News.category_id == cid)

    # 3.查询数据
    try:
        paginate = News.query.filter(*filters).order_by(News.create_time.desc()).paginate(page, per_page, False)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="数据库查询错误")

    # 取到当前页的数据
    news_list = paginate.items  # 模型对象列表
    current_page = paginate.page
    total_pages = paginate.pages

    news_dict_li = []
    for news in news_list:
        news_dict_li.append(news.to_basic_dict())

    data = {
        "total_pages": total_pages,
        "current_page": current_page,
        "news_dict_li": news_dict_li
    }

    return jsonify(errno=RET.OK, errmsg="OK", data=data)


@index_blue.route("/")
@user_login_data
def index():
    """
    显示首页：
    1.如果用户已登录，将当前登录用户的数据传到模板中，供模板使用
    """
    # user_id = session.get("user_id", None)
    # user = None
    # if user_id:
    #     try:
    #         user = User.query.get(user_id)
    #     except Exception as e:
    #         current_app.logger.error(e)
    user = g.user

    # 右侧新闻排行的逻辑实现
    news_list = []
    try:
        news_list = News.query.order_by(News.clicks.desc()).limit(constants.CLICK_RANK_MAX_NEWS)
    except Exception as e:
        current_app.logger.error(e)
    news_dict_li = []
    for news in news_list:
        news_dict_li.append(news.to_basic_dict())

    # 查询分类数据，通过模板形式渲染出来
    categories = Category.query.all()
    category_li = []
    for category in categories:
        category_li.append(category.to_dict())


    data = {
        "user": user.to_dict() if user else None,
        "news_dict_li": news_dict_li,
        "category_li": category_li
    }

    return render_template('news/index.html', data=data)


# send_static_file是flask查找指定静态文件所调用的方法
@index_blue.route("/favicon.ico")
def favicon():
    return current_app.send_static_file('news/favicon.ico')

info/modules/news/__init__.py
from flask import Blueprint

# 创建蓝图对象
news_blue = Blueprint("news",__name__, url_prefix='/news')

from .views import *

info/modules/passport/__init__.py
from flask import Blueprint

# 创建蓝图对象
passport_blue = Blueprint("passport",__name__, url_prefix='/passport')

from .views import *

info/modules/profile/__init__.py
from flask import Blueprint

# 创建蓝图对象
profile_blue = Blueprint("profile",__name__, url_prefix='/user')

from .views import *

info/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block titleBlock %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
    <link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
    {% block linkBlock %}
    {% endblock %}
    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="../../static/news/js/main.js"></script>
    {% block scriptBlock %}
    {% endblock %}
</head>
<body>
    <div class="header_con">
        <div class="header">
            <a href="/" class="logo fl"><img src="../../static/news/images/logo.png" alt="logo"></a>
            {% block categloryBlock %}
            <ul class="menu fl">
                {% for category in data.category_li %}
                    {% if loop.index == 1 %}
                        <li class="active" data-cid="{{ category.id }}"><a href="javascript:;">{{ category.name }}</a></li>
                    {% else %}
                        <li data-cid="{{ category.id }}"><a href="javascript:;">{{ category.name }}</a></li>
                    {% endif %}

                {% endfor %}

            </ul>
            {% endblock %}


            {% if data.user %}
                <!-- 用户登录后显示下面，隐藏上面 -->
                <div class="user_login fr">
                    <img src="{% if data.user.avatar_url %} {{ data.user.avatar_url  }}{% else %}../../static/news/images/person01.png{% endif %}" class="lgin_pic">
                    <a href="{{ url_for("profile.user_info") }}" id="nick_name">{{ data.user.nick_name }}</a>
                    {% block exitBlock %}
                    <a href="javascript:;" onclick="logout()">退出</a>
                    {% endblock %}

                </div>
                {% else %}
                    <div class="user_btns fr">
                    <a href="javascript:;" class="login_btn">登录</a> / <a href="javascript:;" class="register_btn">注册</a>
                </div>
            {% endif %}


        </div>
    </div>

    <div class="conter_con">
        {% block contentBlock %}

        {% endblock %}

        {% block rankBlock %}
            <div class="rank_con fr">
                {% block authorBlock %}
                {% endblock %}
                <div class="rank_title">
                    <h3>点击排行</h3>
                </div>

                <ul class="rank_list">
                     {% for news in data.news_dict_li %}
                        <li><span class={{ loop.index | set_class }}>{{ loop.index }}</span><a href="#">{{ news.title }}</a></li>{% endfor %}
                </ul>
            </div>

        {% endblock %}



    </div>
    {% block bottomBlock %}
    <div class="footer">
        <div class="footer_links">
            <a href="">关于我们</a>
            <span>|</span>
            <a href="">联系我们</a>
            <span>|</span>
            <a href="">招聘人才</a>
            <span>|</span>
            <a href="">友情链接</a>
        </div>
        <p class="copyright">
            CopyRight © 2018 新经资讯信息技术有限公司 All Rights Reserved<br />
电话：010-****888    京ICP备*******8号
        </p>
    </div>
    {% endblock %}


    <!-- 登录表单 -->
    <form class="login_form_con">
        <div class="login_form">
            <div class="login_title">
                <h3>登 录</h3>
                <a href="javascript:;" class="shutoff"></a>
            </div>
            <div class="form_group">
                <input id="mobile" type="text" name="mobile" autocomplete="off">
                <div class="input_tip">手机号</div>
                <div id="login-mobile-err" class="error_tip">手机号不能为空</div>
            </div>
            <div class="form_group">
                <input id="password" type="password" name="password">
                <div class="input_tip">密码(不少于6位)</div>
                <div id="login-password-err" class="error_tip">密码不能为空</div>
            </div>
            <input type="submit" name="" value="登 录" class="input_sub">
            <div class="down_link">还没有账号？<a href="javascript:;" class="to_register">立即注册</a></div>
        </div>
        <div class="mask"></div>
    </form>

    <!-- 注册表单 -->
    <form class="register_form_con">
        <div class="register_form">
            <div class="register_title">
                <h3>注 册</h3>
                <a href="javascript:;" class="shutoff"></a>
            </div>
            <div class="form_group">
                <input type="text" name="mobile" autocomplete="off" id="register_mobile" class="phone_input">
                <div class="input_tip">手机号</div>
                <div id="register-mobile-err" class="error_tip">手机号不能为空</div>
            </div>
            <div class="form_group">
                <input type="text" name="code_pwd" id="imagecode" class="code_pwd">
                <div class="input_tip">图形验证码</div>
                <img src="../../static/news/images/pic_code.png" class="get_pic_code" onclick="generateImageCode()">
                <div id="register-image-code-err" class="error_tip">图形码不能为空</div>
            </div>
            <div class="form_group">
                <input type="text" name="smscode" id="smscode" class="code_pwd">
                <div class="input_tip">手机验证码</div>
                <a href="javascript:;" class="get_code" onclick="sendSMSCode()">点击获取验证码</a>
                <div id="register-sms-code-err" class="error_tip">验证码不能为空</div>
            </div>
            <div class="form_group">
                <input type="password" name="password" id="register_password" class="pass_input">
                <div class="input_tip">密码(不少于6位)</div>
                <div id="register-password-err" class="error_tip">密码不能为空</div>
            </div>
            <div  class="form_group2 clearfix">
                <input type="checkbox" class="agree_input" checked>
                <p>同意使用条款，并已阅读"跟帖评论自律管理承诺书"</p>
                <div class="error_tip">请勾选</div>
            </div>
            <input type="submit" name="" value="注 册" class="input_sub">
            <div class="down_link">已有账号？<a href="javascript:;" class="to_login">立即登录</a></div>
        </div>
        <div class="mask"></div>
    </form>
</body>
</html>

info/templates/news/index.html
{% extends "news/base.html" %}

{% block titleBlock %}
首页-新经资讯
{% endblock %}

{% block scriptBlock %}
<script type="text/javascript" src="../../static/news/js/index.js"></script>
{% endblock %}

{% block contentBlock %}
<ul class="list_con fl">
            <li>
                <a href="#" class="news_pic fl"><img src="../../static/news/images/news_pic.jpg"></a>
                <a href="#" class="news_title fl">日本史上最大IPO之一要来了：软银计划将手机业务分拆上市软银计划将手机业务分拆上市</a>
                <a href="#" class="news_detail fl">据日经新闻网，软银计划让旗下核心业务移动手机部门SoftBank Corp.分拆上市，或募资2万亿日元(约180亿美元)。随着软银逐步向投资公司转型，此举旨在给手机业务部门更多自主权。</a>
                <div class="author_info fl">
                    <div class="author fl">
                        <img src="../../static/news/images/person.png" alt="author">
                        <a href="#">乐鸣</a>
                    </div>
                    <div class="time fl">2017-01-01 00:00:00</div>
                </div>
            </li>
            <li>
                <a href="#" class="news_pic fl"><img src="../../static/news/images/news_pic.jpg"></a>
                <a href="#" class="news_title fl">日本史上最大IPO之一要来了：软银计划将手机业务分拆上市</a>
                <a href="#" class="news_detail fl">据日经新闻网，软银计划让旗下核心业务移动手机部门SoftBank Corp.分拆上市，或募资2万亿日元(约180亿美元)。随着软银逐步向投资公司转型，此举旨在给手机业务部门更多自主权。</a>
                <div class="author_info fl">
                    <div class="source fl">
                        来源：广州日报
                    </div>
                    <div class="time fl">2017-01-01 00:00:00</div>
                </div>
            </li>
            <li>
                <a href="#" class="news_pic fl"><img src="../../static/news/images/news_pic.jpg"></a>
                <a href="#" class="news_title fl">日本史上最大IPO之一要来了：软银计划将手机业务分拆上市</a>
                <a href="#" class="news_detail fl">据日经新闻网，软银计划让旗下核心业务移动手机部门SoftBank Corp.分拆上市，或募资2万亿日元(约180亿美元)。随着软银逐步向投资公司转型，此举旨在给手机业务部门更多自主权。</a>
                <div class="author_info fl">
                    <div class="author fl">
                        <img src="../../static/news/images/person.png" alt="author">
                        <a href="#">乐鸣</a>
                    </div>
                    <div class="time fl">2017-01-01 00:00:00</div>
                </div>
            </li>
            <li>
                <a href="#" class="news_pic fl"><img src="../../static/news/images/news_pic.jpg"></a>
                <a href="#" class="news_title fl">日本史上最大IPO之一要来了：软银计划将手机业务分拆上市</a>
                <a href="#" class="news_detail fl">据日经新闻网，软银计划让旗下核心业务移动手机部门SoftBank Corp.分拆上市，或募资2万亿日元(约180亿美元)。随着软银逐步向投资公司转型，此举旨在给手机业务部门更多自主权。</a>
                <div class="author_info fl">
                    <div class="source fl">
                        来源：广州日报
                    </div>
                    <div class="time fl">2017-01-01 00:00:00</div>
                </div>
            </li>
        </ul>
{% endblock %}

info/templates/news/user.html
{% extends "news/base.html" %}

{% block titleBlock %}
    用户中心
{% endblock %}

{% block categloryBlock %}
{% endblock %}

{% block rankBlock %}

{% endblock %}

{% block contentBlock %}
<div class="user_menu_con fl">
    <div class="user_center_pic">
        <img src={% if data.user.avatar_url %}{{ data.user.avatar_url }}{% else %}"../../static/news/images/user_pic.png"{% endif %} alt="用户图片">
    </div>
    <div class="user_center_name">{{ data.user.nick_name }}</div>

    <ul class="option_list">
        <li class="active"><a href="{{ url_for("profile.base_info") }}" target="main_frame">基本资料</a></li>
        <li><a href="{{ url_for("profile.pic_info") }}" target="main_frame">头像设置</a></li>
        <li><a href="{{ url_for("profile.user_follow") }}" target="main_frame">我的关注</a></li>
        <li><a href="{{ url_for("profile.pass_info") }}" target="main_frame">密码修改</a></li>
        <li><a href="{{ url_for("profile.user_collection") }}" target="main_frame">我的收藏</a></li>
        <li><a href="{{ url_for("profile.news_release") }}" target="main_frame">新闻发布</a></li>
        <li><a href="{{ url_for("profile.news_list") }}" target="main_frame">新闻列表</a></li>
    </ul>
</div>
<div class="user_con fr">
    <iframe src="{{ url_for("profile.base_info") }}" frameborder="0" name="main_frame" class="main_frame" id="main_frame"></iframe>
</div>
{% endblock %}

info/templates/news/user_pass_info.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>用户中心</title>
	<link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
	<link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
        <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="../../static/news/js/user_pass_info.js"></script>
</head>
<body class="inframe_body">
    <form class="pass_info">
        <h3>密码修改</h3>
        <div class="form-group">
            <label>当前密码：</label>
            <input type="password" name="old_password" class="input_txt">
        </div>
        <div class="form-group">
            <label>新密码：</label>
            <input type="password" name="new_password" class="input_txt">
        </div>
        <div class="form-group">
            <label>确认密码：</label>
            <input type="password" name="new_password2" class="input_txt">
        </div>
       <div class="error_tip">提示信息</div>
        <div class="form-group">
            <input type="submit" value="保 存" class="input_sub">
        </div>
    </form>
</body>
</html>